### PR TITLE
Disable cloud-init networking

### PR DESCRIPTION
**Pull request by michalskrivanek**
Let OS do the right thing instead of depending on buggy cloud-init

### CODE REVIEW

**Review by sandrobonazzola — CHANGES_REQUESTED** [review]
Can you please provide some insight on what failed and where? Also,did you verify this is working?

**Comment by michalskrivanek** [comment]
this is being tested

it was identified in OST running on latest el[89]stream where cloud-init seems to persist its configuration in NetworkManager that breaks the final intended HE VM network configuration

**Comment by michalskrivanek** [comment]
tested on IPv4-only and dual stack and it seems to do the right thing. I think it's the safest thing to do because cloud-init is plagued with bugs like that

The effect is that there is no persisted NM "cloud-init" connection configured and system just uses "normal" dhcp.
AFAICT this was the intention of the original code that used initscripts, we don't do anything else to the network config, so disabling and letting OS handle that looks ok to me.

@didib @arachmani thoughts?

**Comment by michalskrivanek** [comment]
it is likely a cloud-init or networkmanager bug, but i don't see why we need to deal with it in future This doesn't disable networking, it just disables cloud-init's handling of networking setup, and we do not attempt to do anything there other than using DHCP.

**Comment by michalskrivanek** [comment]
verified with IPv6-only too. Looks safe enough

**Comment by didib** [comment]
IIRC OST supports only testing HE deploy with the engine VM getting its network config via dhcp, right? But HE deploy supports also static config. IIUC this is done via cloud-init as well. Not sure how this is relevant to current patch, but we must make sure we do not break this. Did you test static network config?

**Comment by didib** [comment]
Wrote the previous comment without noticing that it's already merged :-). Anyway, I'd also like a Bug-Url with more details there. Too late, but perhaps on the next patch if needed...

**Pull request merged**
