### PR TITLE
github: upload to -copr or -cbs directories

### PR DESCRIPTION
**Pull request by michalskrivanek**
now that we can build against COPR or CBS packages let's separate the repos at resources.ovirt.org accordingly

### CODE REVIEW

**Comment by michalskrivanek** [comment]
@didib 
I think it works, however the CBS build does not.  the job times out...do you think it's just that slow?

**Comment by didib** [comment]
> @didib I think it works, however the CBS build does not. the job times out...do you think it's just that slow?

No idea. Can we see where it times out? Do we know that it generally works there? IIRC cbs has rather severe limits on access, as it's rather small - not intended for mass consumption. But IIUC we only/mostly use it for the release rpm, not the actual project ones (engine etc.). So need to understand where it fails.

**Comment by michalskrivanek** [comment]
let's try longer...

**Comment by michalskrivanek** [comment]
https://github.com/oVirt/ovirt-appliance/actions/runs/3828409253/jobs/6513961786

**Comment by michalskrivanek** [comment]
ah, only now i noticed:
09:52:16,400 INFO anaconda:program: ++ find '/etc/yum.repos.d/ovirt*.repo' -type f '!' -name '*dep*'
09:52:16,401 INFO anaconda:program: find: '/etc/yum.repos.d/ovirt*.repo': No such file or directory
09:52:16,401 INFO anaconda:program: + sed -i 's/^mirrorlist/#mirrorlist/ ; s/^#baseurl/baseurl/'
09:52:16,401 INFO anaconda:program: sed: no input files
09:52:16,401 DEBUG anaconda:program: Return code: 4
09:52:16,402 ERR anaconda:anaconda: kickstart.script: Error code 4 running the kickstart script at line 123

**Comment by michalskrivanek** [comment]
https://github.com/oVirt/ovirt-appliance/actions/runs/3829630782

**Comment by michalskrivanek** [comment]
one last test: https://github.com/oVirt/ovirt-appliance/actions/runs/3830781855

**Pull request merged**
